// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzHvh5slGlmhxnqR1Fj5a64QkR29coE6Q',
    appId: '1:1015339619177:web:32b3468615b5a4bb61e3f8',
    messagingSenderId: '1015339619177',
    projectId: 'murakib-401b4',
    authDomain: 'murakib-401b4.firebaseapp.com',
    storageBucket: 'murakib-401b4.firebasestorage.app',
    measurementId: 'G-DSFQFPRVC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTBHYjoTw6Ljh22KaNxIEPNHaqPVMCZBE',
    appId: '1:1015339619177:android:16fc4958d31ea14261e3f8',
    messagingSenderId: '1015339619177',
    projectId: 'murakib-401b4',
    storageBucket: 'murakib-401b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCacKPh6tN_DU2-_UsdX2arH41S1cFDLQo',
    appId: '1:1015339619177:ios:bb123a764f13c43d61e3f8',
    messagingSenderId: '1015339619177',
    projectId: 'murakib-401b4',
    storageBucket: 'murakib-401b4.firebasestorage.app',
    iosBundleId: 'com.murakib.murakibVip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCacKPh6tN_DU2-_UsdX2arH41S1cFDLQo',
    appId: '1:1015339619177:ios:bb123a764f13c43d61e3f8',
    messagingSenderId: '1015339619177',
    projectId: 'murakib-401b4',
    storageBucket: 'murakib-401b4.firebasestorage.app',
    iosBundleId: 'com.murakib.murakibVip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhQu_7iYZwZiudVR22x87GOenImydtE1Y',
    appId: '1:1015339619177:web:299db319bd7743ec61e3f8',
    messagingSenderId: '1015339619177',
    projectId: 'murakib-401b4',
    authDomain: 'murakib-401b4.firebaseapp.com',
    storageBucket: 'murakib-401b4.firebasestorage.app',
    measurementId: 'G-GB0XJ3XXH5',
  );
}
